# Generated by Django 3.2.9 on 2022-04-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_id_accountpointlog_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountPointLog',
            new_name='AccountPoint',
        ),
        migrations.AlterModelTable(
            name='accountpoint',
            table='account_point',
        ),
    ]
