# Generated by Django 3.2.9 on 2022-04-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220403_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpoint',
            old_name='point',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='accountwithdraw',
            old_name='point',
            new_name='amount',
        ),
    ]
