# Generated by Django 3.2.9 on 2022-04-04 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220403_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountwithdraw',
            old_name='bank',
            new_name='bank_account',
        ),
        migrations.AlterField(
            model_name='accountpoint',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountpoint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accountwithdraw',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountwithdraw',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
