# Generated by Django 3.2.9 on 2022-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountuseraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuseraddress',
            old_name='address',
            new_name='base_address',
        ),
        migrations.RenameField(
            model_name='accountuseraddress',
            old_name='full_name',
            new_name='detail_address',
        ),
        migrations.AddField(
            model_name='accountuseraddress',
            name='receiver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
