# Generated by Django 3.2.9 on 2022-04-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220404_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuseraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
