# Generated by Django 3.2.9 on 2022-04-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_accountuseraddress_is_default'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountPoint',
            new_name='UserPoint',
        ),
        migrations.RenameModel(
            old_name='AccountWithdraw',
            new_name='UserWithdraw',
        ),
        migrations.AlterModelTable(
            name='userpoint',
            table='account_user_point',
        ),
        migrations.AlterModelTable(
            name='userwithdraw',
            table='account_user_withdraw',
        ),
    ]
