# Generated by Django 3.2.9 on 2022-04-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220404_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountUserAddress',
            new_name='UserShippingAddress',
        ),
        migrations.AlterModelTable(
            name='usershippingaddress',
            table='account_user_shipping_address',
        ),
    ]
