# Generated by Django 3.2.9 on 2022-04-04 17:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_usermessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(blank=True, upload_to=account.models.upload_to),
        ),
    ]
