# Generated by Django 3.2.9 on 2022-04-07 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
