# Generated by Django 3.2.9 on 2022-04-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
    ]
