# Generated by Django 3.2.9 on 2022-04-09 00:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220408_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avater.jpg', upload_to=account.models.upload_to),
        ),
    ]
