# Generated by Django 3.2.9 on 2022-04-06 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_user_avater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=255)),
                ('pg', models.CharField(max_length=255)),
                ('paid_amount', models.IntegerField()),
                ('paid_at', models.DateTimeField(default=datetime.datetime.now)),
                ('merchant_uid', models.CharField(max_length=255)),
                ('imp_uid', models.CharField(max_length=255)),
                ('apply_num', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
