# Generated by Django 3.2.9 on 2022-04-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_gigcampaign_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigCampaign',
        ),
    ]
