# Generated by Django 3.2.9 on 2022-04-04 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_user_avater'),
        ('gig', '0003_delete_gigcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('provide', models.CharField(max_length=255)),
                ('guide', models.TextField()),
                ('require', models.CharField(max_length=255)),
                ('limit_offer', models.IntegerField()),
                ('total_offer', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('cosmetic', '코스메틱'), ('beauty', '미용'), ('fashion', '패션/잡화'), ('food', '식품'), ('supplies', '생활용품'), ('baby', '출산/육아'), ('digital', '디지털/가전'), ('sports', '스포츠/건강'), ('pet', '반려동물'), ('restaurant', '맛집'), ('travel', '여행/숙박'), ('area', '지역/문화'), ('etc', '기타')], max_length=255)),
                ('campaign_type', models.CharField(choices=[('delivery', '배송형'), ('visit', '방문형'), ('reporter', '기자단'), ('buy', '구매형'), ('live_commerce', '라이브커머스')], max_length=255)),
                ('channel', models.CharField(choices=[('n_blog', 'Nblog'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('n_cafe', 'Ncafe'), ('n_post', 'Npost'), ('etc', 'Etc')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('finished_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'gig_campaign',
                'managed': True,
            },
        ),
    ]
