# Generated by Django 3.2.9 on 2022-04-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0004_gigcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='require',
        ),
    ]
