# Generated by Django 3.2.9 on 2022-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0005_remove_gigcampaign_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
