# Generated by Django 3.2.9 on 2022-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0006_gigcampaign_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='point',
            new_name='reward',
        ),
        migrations.AlterField(
            model_name='gigcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('delivery', '배송형'), ('visit', '방문형'), ('reporter', '기자단'), ('buy', '구매형')], max_length=255),
        ),
    ]
