# Generated by Django 3.2.9 on 2022-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0007_auto_20220405_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='guide',
            new_name='guide_line',
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='product_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
