# Generated by Django 3.2.9 on 2022-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0009_auto_20220406_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigcampaign',
            name='merchant',
            field=models.CharField(max_length=6),
        ),
    ]
