# Generated by Django 3.2.9 on 2022-04-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_avater'),
        ('gig', '0011_auto_20220406_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', to='account.User'),
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='offer_user',
            field=models.ManyToManyField(blank=True, related_name='offer_user_set', to='account.User'),
        ),
    ]
