# Generated by Django 3.2.9 on 2022-04-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0012_auto_20220406_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='like_user',
            new_name='favorite_user',
        ),
    ]
