# Generated by Django 3.2.9 on 2022-04-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0013_rename_like_user_gigcampaign_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='favorite_user',
            new_name='favorite',
        ),
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='offer_user',
            new_name='offer',
        ),
    ]
