# Generated by Django 3.2.9 on 2022-04-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0014_auto_20220406_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='favorite',
            new_name='favorite_user',
        ),
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='offer',
            new_name='offer_user',
        ),
    ]
