# Generated by Django 3.2.9 on 2022-04-07 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_avater'),
        ('gig', '0019_remove_gigcampaign_favorite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCampaignFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('favorite_at', models.DateTimeField(default=datetime.datetime.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'gig_campaign_favorite',
                'managed': True,
            },
        ),
    ]
