# Generated by Django 3.2.9 on 2022-04-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0020_gigcampaignfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignfavorite',
            name='place',
        ),
    ]
