# Generated by Django 3.2.9 on 2022-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_avater'),
        ('gig', '0022_gigcampaign_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='total_offer',
        ),
        migrations.AlterField(
            model_name='gigcampaign',
            name='favorite_user',
            field=models.ManyToManyField(blank=True, related_name='favorite_user_set', through='gig.GigCampaignFavorite', to='account.User'),
        ),
    ]
