# Generated by Django 3.2.9 on 2022-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0023_auto_20220407_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='item',
            field=models.BooleanField(default=False),
        ),
    ]
