# Generated by Django 3.2.9 on 2022-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0024_gigcampaign_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='item',
            new_name='is_item',
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
