# Generated by Django 3.2.9 on 2022-04-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0025_auto_20220407_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigcampaign',
            old_name='is_main',
            new_name='is_recommend',
        ),
    ]
