# Generated by Django 3.2.9 on 2022-04-08 06:10

from django.db import migrations, models
import gig.models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0026_rename_is_main_gigcampaign_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=gig.models.upload_to),
            preserve_default=False,
        ),
    ]
