# Generated by Django 3.2.9 on 2022-04-08 09:37

from django.db import migrations, models
import gig.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0027_gigcampaign_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='merchant',
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='merchant_uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gigcampaign',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=gig.models.upload_to),
        ),
    ]
