# Generated by Django 3.2.9 on 2022-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0028_auto_20220408_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='offer_user',
        ),
        migrations.AlterField(
            model_name='gigcampaign',
            name='merchant_uid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
