# Generated by Django 3.2.9 on 2022-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0030_auto_20220408_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='sns_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
