# Generated by Django 3.2.9 on 2022-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0031_gigcampaignoffer_sns_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='base_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='detail_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='receiver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
