# Generated by Django 3.2.9 on 2022-04-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220408_1221'),
        ('gig', '0032_auto_20220408_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='base_address',
        ),
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='detail_address',
        ),
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='gigcampaignoffer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.usershippingaddress'),
            preserve_default=False,
        ),
    ]
