# Generated by Django 3.2.9 on 2022-04-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0033_auto_20220408_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaignfavorite',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
    ]
