# Generated by Django 3.2.9 on 2022-04-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0034_gigcampaignfavorite_is_picked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignfavorite',
            name='is_picked',
        ),
        migrations.AddField(
            model_name='gigcampaignoffer',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
    ]
