# Generated by Django 3.2.9 on 2022-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0035_auto_20220409_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='review_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
