# Generated by Django 3.2.9 on 2022-04-09 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_avater'),
        ('gig', '0036_gigcampaign_review_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='review_url',
        ),
        migrations.CreateModel(
            name='GigCampaignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_picked', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'gig_campaign_review',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='review_user',
            field=models.ManyToManyField(blank=True, related_name='review_user_set', through='gig.GigCampaignReview', to='account.User'),
        ),
    ]
