# Generated by Django 3.2.9 on 2022-04-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0037_auto_20220409_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignreview',
            name='is_picked',
        ),
    ]
