# Generated by Django 4.0.4 on 2022-04-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0038_remove_gigcampaignreview_is_picked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='review_user',
        ),
        migrations.DeleteModel(
            name='GigCampaignReview',
        ),
    ]
