# Generated by Django 4.0.4 on 2022-04-13 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0039_remove_gigcampaign_review_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCampaignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gig_campaign_review',
                'managed': True,
            },
        ),
    ]
