# Generated by Django 4.0.4 on 2022-04-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0040_gigcampaignreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaignreview',
            name='user',
        ),
    ]
