# Generated by Django 4.0.4 on 2022-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0042_alter_gigcampaignreview_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaignreview',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
