# Generated by Django 3.2.9 on 2022-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hit', models.IntegerField()),
            ],
            options={
                'db_table': 'support_qna',
                'managed': True,
            },
        ),
    ]
