# Generated by Django 3.2.9 on 2022-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportqna_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportqna',
            name='target',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
