# Generated by Django 3.2.9 on 2022-04-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportqna_target'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportQna',
            new_name='SupportFaq',
        ),
        migrations.AlterModelTable(
            name='supportfaq',
            table='support_faq',
        ),
    ]
