# Generated by Django 3.2.9 on 2022-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20220411_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfaq',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
